// Code generated by scripts/gen-rpc-types.sh from proto/milliways.json. DO NOT EDIT.
// Proto version: 0.1

// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package rpc

import "encoding/json"
import "fmt"
import "reflect"
import "time"

// Stable identifier for a runner. User-facing ids are lowercase letters; reserved
// internal ids are prefixed with underscore.
type AgentID string

// UnmarshalJSON implements json.Unmarshaler.
func (j *AgentID) UnmarshalJSON(value []byte) error {
	type Plain AgentID
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AgentID(plain)
	return nil
}

// One entry from agent.list.
type AgentInfo struct {
	// AuthStatus corresponds to the JSON schema field "auth_status".
	AuthStatus AgentInfoAuthStatus `json:"auth_status" yaml:"auth_status" mapstructure:"auth_status"`

	// Available corresponds to the JSON schema field "available".
	Available bool `json:"available" yaml:"available" mapstructure:"available"`

	// ID corresponds to the JSON schema field "id".
	ID AgentID `json:"id" yaml:"id" mapstructure:"id"`

	// Model corresponds to the JSON schema field "model".
	Model *string `json:"model,omitempty,omitzero" yaml:"model,omitempty" mapstructure:"model,omitempty"`
}

type AgentInfoAuthStatus string

const AgentInfoAuthStatusExpired AgentInfoAuthStatus = "expired"
const AgentInfoAuthStatusMissingCredentials AgentInfoAuthStatus = "missing_credentials"
const AgentInfoAuthStatusOK AgentInfoAuthStatus = "ok"
const AgentInfoAuthStatusUnknown AgentInfoAuthStatus = "unknown"

var enumValues_AgentInfoAuthStatus = []interface{}{
	"ok",
	"missing_credentials",
	"expired",
	"unknown",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AgentInfoAuthStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AgentInfoAuthStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_AgentInfoAuthStatus, v)
	}
	*j = AgentInfoAuthStatus(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AgentInfo) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["auth_status"]; raw != nil && !ok {
		return fmt.Errorf("field auth_status in AgentInfo: required")
	}
	if _, ok := raw["available"]; raw != nil && !ok {
		return fmt.Errorf("field available in AgentInfo: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in AgentInfo: required")
	}
	type Plain AgentInfo
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AgentInfo(plain)
	return nil
}

// Aggregated /context across all agents. Returned by context.get_all.
type AggregateContext struct {
	// Agents corresponds to the JSON schema field "agents".
	Agents []ContextSnapshot `json:"agents" yaml:"agents" mapstructure:"agents"`

	// RecentRouting corresponds to the JSON schema field "recent_routing".
	RecentRouting []RoutingDecision `json:"recent_routing,omitempty,omitzero" yaml:"recent_routing,omitempty" mapstructure:"recent_routing,omitempty"`

	// Totals corresponds to the JSON schema field "totals".
	Totals AggregateContextTotals `json:"totals" yaml:"totals" mapstructure:"totals"`
}

type AggregateContextTotals struct {
	// ActiveAgents corresponds to the JSON schema field "active_agents".
	ActiveAgents int `json:"active_agents" yaml:"active_agents" mapstructure:"active_agents"`

	// Cached corresponds to the JSON schema field "cached".
	Cached int `json:"cached" yaml:"cached" mapstructure:"cached"`

	// CostUsd corresponds to the JSON schema field "cost_usd".
	CostUsd float64 `json:"cost_usd" yaml:"cost_usd" mapstructure:"cost_usd"`

	// Errors5M corresponds to the JSON schema field "errors_5m".
	Errors5M int `json:"errors_5m" yaml:"errors_5m" mapstructure:"errors_5m"`

	// TokensIn corresponds to the JSON schema field "tokens_in".
	TokensIn int `json:"tokens_in" yaml:"tokens_in" mapstructure:"tokens_in"`

	// TokensOut corresponds to the JSON schema field "tokens_out".
	TokensOut int `json:"tokens_out" yaml:"tokens_out" mapstructure:"tokens_out"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AggregateContextTotals) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["active_agents"]; raw != nil && !ok {
		return fmt.Errorf("field active_agents in AggregateContextTotals: required")
	}
	if _, ok := raw["cached"]; raw != nil && !ok {
		return fmt.Errorf("field cached in AggregateContextTotals: required")
	}
	if _, ok := raw["cost_usd"]; raw != nil && !ok {
		return fmt.Errorf("field cost_usd in AggregateContextTotals: required")
	}
	if _, ok := raw["errors_5m"]; raw != nil && !ok {
		return fmt.Errorf("field errors_5m in AggregateContextTotals: required")
	}
	if _, ok := raw["tokens_in"]; raw != nil && !ok {
		return fmt.Errorf("field tokens_in in AggregateContextTotals: required")
	}
	if _, ok := raw["tokens_out"]; raw != nil && !ok {
		return fmt.Errorf("field tokens_out in AggregateContextTotals: required")
	}
	type Plain AggregateContextTotals
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.ActiveAgents {
		return fmt.Errorf("field %s: must be >= %v", "active_agents", 0)
	}
	if 0 > plain.Cached {
		return fmt.Errorf("field %s: must be >= %v", "cached", 0)
	}
	if 0 > plain.CostUsd {
		return fmt.Errorf("field %s: must be >= %v", "cost_usd", 0)
	}
	if 0 > plain.Errors5M {
		return fmt.Errorf("field %s: must be >= %v", "errors_5m", 0)
	}
	if 0 > plain.TokensIn {
		return fmt.Errorf("field %s: must be >= %v", "tokens_in", 0)
	}
	if 0 > plain.TokensOut {
		return fmt.Errorf("field %s: must be >= %v", "tokens_out", 0)
	}
	*j = AggregateContextTotals(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AggregateContext) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["agents"]; raw != nil && !ok {
		return fmt.Errorf("field agents in AggregateContext: required")
	}
	if _, ok := raw["totals"]; raw != nil && !ok {
		return fmt.Errorf("field totals in AggregateContext: required")
	}
	type Plain AggregateContext
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AggregateContext(plain)
	return nil
}

type BarsChart struct {
	// DataHash corresponds to the JSON schema field "data_hash".
	DataHash string `json:"data_hash" yaml:"data_hash" mapstructure:"data_hash"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Series corresponds to the JSON schema field "series".
	Series []BarsChartSeriesElem `json:"series" yaml:"series" mapstructure:"series"`

	// XLabels corresponds to the JSON schema field "x_labels".
	XLabels []string `json:"x_labels,omitempty,omitzero" yaml:"x_labels,omitempty" mapstructure:"x_labels,omitempty"`
}

type BarsChartSeriesElem struct {
	// Hint corresponds to the JSON schema field "hint".
	Hint *Hint `json:"hint,omitempty,omitzero" yaml:"hint,omitempty" mapstructure:"hint,omitempty"`

	// Label corresponds to the JSON schema field "label".
	Label string `json:"label" yaml:"label" mapstructure:"label"`

	// Values corresponds to the JSON schema field "values".
	Values []float64 `json:"values" yaml:"values" mapstructure:"values"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BarsChartSeriesElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["label"]; raw != nil && !ok {
		return fmt.Errorf("field label in BarsChartSeriesElem: required")
	}
	if _, ok := raw["values"]; raw != nil && !ok {
		return fmt.Errorf("field values in BarsChartSeriesElem: required")
	}
	type Plain BarsChartSeriesElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = BarsChartSeriesElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BarsChart) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["data_hash"]; raw != nil && !ok {
		return fmt.Errorf("field data_hash in BarsChart: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in BarsChart: required")
	}
	if _, ok := raw["series"]; raw != nil && !ok {
		return fmt.Errorf("field series in BarsChart: required")
	}
	type Plain BarsChart
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Kind != "bars" {
		return fmt.Errorf("field %s: must be equal to %s", "kind", "bars")
	}
	*j = BarsChart(plain)
	return nil
}

// A single rollup bucket. The shape is uniform across tiers and metric kinds;
// fields not relevant to the kind are omitted.
type Bucket struct {
	// Count corresponds to the JSON schema field "count".
	Count *int `json:"count,omitempty,omitzero" yaml:"count,omitempty" mapstructure:"count,omitempty"`

	// Max corresponds to the JSON schema field "max".
	Max *float64 `json:"max,omitempty,omitzero" yaml:"max,omitempty" mapstructure:"max,omitempty"`

	// Min corresponds to the JSON schema field "min".
	Min *float64 `json:"min,omitempty,omitzero" yaml:"min,omitempty" mapstructure:"min,omitempty"`

	// P50 corresponds to the JSON schema field "p50".
	P50 *float64 `json:"p50,omitempty,omitzero" yaml:"p50,omitempty" mapstructure:"p50,omitempty"`

	// P95 corresponds to the JSON schema field "p95".
	P95 *float64 `json:"p95,omitempty,omitzero" yaml:"p95,omitempty" mapstructure:"p95,omitempty"`

	// P99 corresponds to the JSON schema field "p99".
	P99 *float64 `json:"p99,omitempty,omitzero" yaml:"p99,omitempty" mapstructure:"p99,omitempty"`

	// Sum corresponds to the JSON schema field "sum".
	Sum *float64 `json:"sum,omitempty,omitzero" yaml:"sum,omitempty" mapstructure:"sum,omitempty"`

	// Start of the bucket window.
	Ts time.Time `json:"ts" yaml:"ts" mapstructure:"ts"`

	// Counter total or gauge mean.
	Value *float64 `json:"value,omitempty,omitzero" yaml:"value,omitempty" mapstructure:"value,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Bucket) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["ts"]; raw != nil && !ok {
		return fmt.Errorf("field ts in Bucket: required")
	}
	type Plain Bucket
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Count != nil && 0 > *plain.Count {
		return fmt.Errorf("field %s: must be >= %v", "count", 0)
	}
	*j = Bucket(plain)
	return nil
}

// Structured chart data emitted by context.chart_data. Rust-side renders the
// actual PNG via the plotters crate (Decision 12). The daemon never emits PNG
// bytes or kitty-graphics escapes.
type ChartData interface{}

type ChartKind string

const ChartKindBars ChartKind = "bars"
const ChartKindDonut ChartKind = "donut"
const ChartKindLine ChartKind = "line"
const ChartKindSparkline ChartKind = "sparkline"

var enumValues_ChartKind = []interface{}{
	"donut",
	"sparkline",
	"bars",
	"line",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ChartKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ChartKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ChartKind, v)
	}
	*j = ChartKind(v)
	return nil
}

// Full per-agent context for the /context overlay. Returned by context.get and
// pushed by context.subscribe.
type ContextSnapshot struct {
	// AgentID corresponds to the JSON schema field "agent_id".
	AgentID AgentID `json:"agent_id" yaml:"agent_id" mapstructure:"agent_id"`

	// CostUsd corresponds to the JSON schema field "cost_usd".
	CostUsd *float64 `json:"cost_usd,omitempty,omitzero" yaml:"cost_usd,omitempty" mapstructure:"cost_usd,omitempty"`

	// Errors5M corresponds to the JSON schema field "errors_5m".
	Errors5M *int `json:"errors_5m,omitempty,omitzero" yaml:"errors_5m,omitempty" mapstructure:"errors_5m,omitempty"`

	// FilesInContext corresponds to the JSON schema field "files_in_context".
	FilesInContext []ContextSnapshotFilesInContextElem `json:"files_in_context,omitempty,omitzero" yaml:"files_in_context,omitempty" mapstructure:"files_in_context,omitempty"`

	// LastSpan corresponds to the JSON schema field "last_span".
	LastSpan *Span `json:"last_span,omitempty,omitzero" yaml:"last_span,omitempty" mapstructure:"last_span,omitempty"`

	// MCPServers corresponds to the JSON schema field "mcp_servers".
	MCPServers []ContextSnapshotMCPServersElem `json:"mcp_servers,omitempty,omitzero" yaml:"mcp_servers,omitempty" mapstructure:"mcp_servers,omitempty"`

	// Model corresponds to the JSON schema field "model".
	Model *string `json:"model,omitempty,omitzero" yaml:"model,omitempty" mapstructure:"model,omitempty"`

	// SessionID corresponds to the JSON schema field "session_id".
	SessionID *SessionID `json:"session_id,omitempty,omitzero" yaml:"session_id,omitempty" mapstructure:"session_id,omitempty"`

	// SystemPromptSummary corresponds to the JSON schema field
	// "system_prompt_summary".
	SystemPromptSummary *string `json:"system_prompt_summary,omitempty,omitzero" yaml:"system_prompt_summary,omitempty" mapstructure:"system_prompt_summary,omitempty"`

	// Tokens corresponds to the JSON schema field "tokens".
	Tokens *ContextSnapshotTokens `json:"tokens,omitempty,omitzero" yaml:"tokens,omitempty" mapstructure:"tokens,omitempty"`

	// Tools corresponds to the JSON schema field "tools".
	Tools []ContextSnapshotToolsElem `json:"tools,omitempty,omitzero" yaml:"tools,omitempty" mapstructure:"tools,omitempty"`

	// Turn corresponds to the JSON schema field "turn".
	Turn *int `json:"turn,omitempty,omitzero" yaml:"turn,omitempty" mapstructure:"turn,omitempty"`
}

type ContextSnapshotFilesInContextElem struct {
	// Bytes corresponds to the JSON schema field "bytes".
	Bytes int `json:"bytes" yaml:"bytes" mapstructure:"bytes"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path" yaml:"path" mapstructure:"path"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ContextSnapshotFilesInContextElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["bytes"]; raw != nil && !ok {
		return fmt.Errorf("field bytes in ContextSnapshotFilesInContextElem: required")
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in ContextSnapshotFilesInContextElem: required")
	}
	type Plain ContextSnapshotFilesInContextElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.Bytes {
		return fmt.Errorf("field %s: must be >= %v", "bytes", 0)
	}
	*j = ContextSnapshotFilesInContextElem(plain)
	return nil
}

type ContextSnapshotMCPServersElem struct {
	// Connected corresponds to the JSON schema field "connected".
	Connected bool `json:"connected" yaml:"connected" mapstructure:"connected"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// ToolCount corresponds to the JSON schema field "tool_count".
	ToolCount int `json:"tool_count" yaml:"tool_count" mapstructure:"tool_count"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ContextSnapshotMCPServersElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["connected"]; raw != nil && !ok {
		return fmt.Errorf("field connected in ContextSnapshotMCPServersElem: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ContextSnapshotMCPServersElem: required")
	}
	if _, ok := raw["tool_count"]; raw != nil && !ok {
		return fmt.Errorf("field tool_count in ContextSnapshotMCPServersElem: required")
	}
	type Plain ContextSnapshotMCPServersElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.ToolCount {
		return fmt.Errorf("field %s: must be >= %v", "tool_count", 0)
	}
	*j = ContextSnapshotMCPServersElem(plain)
	return nil
}

type ContextSnapshotTokens struct {
	// Cached corresponds to the JSON schema field "cached".
	Cached int `json:"cached" yaml:"cached" mapstructure:"cached"`

	// Input corresponds to the JSON schema field "input".
	Input int `json:"input" yaml:"input" mapstructure:"input"`

	// Output corresponds to the JSON schema field "output".
	Output int `json:"output" yaml:"output" mapstructure:"output"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ContextSnapshotTokens) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["cached"]; raw != nil && !ok {
		return fmt.Errorf("field cached in ContextSnapshotTokens: required")
	}
	if _, ok := raw["input"]; raw != nil && !ok {
		return fmt.Errorf("field input in ContextSnapshotTokens: required")
	}
	if _, ok := raw["output"]; raw != nil && !ok {
		return fmt.Errorf("field output in ContextSnapshotTokens: required")
	}
	type Plain ContextSnapshotTokens
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.Cached {
		return fmt.Errorf("field %s: must be >= %v", "cached", 0)
	}
	if 0 > plain.Input {
		return fmt.Errorf("field %s: must be >= %v", "input", 0)
	}
	if 0 > plain.Output {
		return fmt.Errorf("field %s: must be >= %v", "output", 0)
	}
	*j = ContextSnapshotTokens(plain)
	return nil
}

type ContextSnapshotToolsElem struct {
	// LastUsedTs corresponds to the JSON schema field "last_used_ts".
	LastUsedTs *time.Time `json:"last_used_ts,omitempty,omitzero" yaml:"last_used_ts,omitempty" mapstructure:"last_used_ts,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ContextSnapshotToolsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ContextSnapshotToolsElem: required")
	}
	type Plain ContextSnapshotToolsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ContextSnapshotToolsElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ContextSnapshot) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["agent_id"]; raw != nil && !ok {
		return fmt.Errorf("field agent_id in ContextSnapshot: required")
	}
	type Plain ContextSnapshot
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.CostUsd != nil && 0 > *plain.CostUsd {
		return fmt.Errorf("field %s: must be >= %v", "cost_usd", 0)
	}
	if plain.Errors5M != nil && 0 > *plain.Errors5M {
		return fmt.Errorf("field %s: must be >= %v", "errors_5m", 0)
	}
	if plain.Turn != nil && 0 > *plain.Turn {
		return fmt.Errorf("field %s: must be >= %v", "turn", 0)
	}
	*j = ContextSnapshot(plain)
	return nil
}

type DonutChart struct {
	// DataHash corresponds to the JSON schema field "data_hash".
	DataHash string `json:"data_hash" yaml:"data_hash" mapstructure:"data_hash"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Segments corresponds to the JSON schema field "segments".
	Segments []DonutChartSegmentsElem `json:"segments" yaml:"segments" mapstructure:"segments"`

	// Total corresponds to the JSON schema field "total".
	Total *float64 `json:"total,omitempty,omitzero" yaml:"total,omitempty" mapstructure:"total,omitempty"`
}

type DonutChartSegmentsElem struct {
	// Hint corresponds to the JSON schema field "hint".
	Hint *Hint `json:"hint,omitempty,omitzero" yaml:"hint,omitempty" mapstructure:"hint,omitempty"`

	// Label corresponds to the JSON schema field "label".
	Label string `json:"label" yaml:"label" mapstructure:"label"`

	// Value corresponds to the JSON schema field "value".
	Value float64 `json:"value" yaml:"value" mapstructure:"value"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DonutChartSegmentsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["label"]; raw != nil && !ok {
		return fmt.Errorf("field label in DonutChartSegmentsElem: required")
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in DonutChartSegmentsElem: required")
	}
	type Plain DonutChartSegmentsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.Value {
		return fmt.Errorf("field %s: must be >= %v", "value", 0)
	}
	*j = DonutChartSegmentsElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DonutChart) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["data_hash"]; raw != nil && !ok {
		return fmt.Errorf("field data_hash in DonutChart: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in DonutChart: required")
	}
	if _, ok := raw["segments"]; raw != nil && !ok {
		return fmt.Errorf("field segments in DonutChart: required")
	}
	type Plain DonutChart
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Kind != "donut" {
		return fmt.Errorf("field %s: must be equal to %s", "kind", "donut")
	}
	*j = DonutChart(plain)
	return nil
}

type Hint string

const HintAccent Hint = "accent"
const HintDim Hint = "dim"
const HintErr Hint = "err"
const HintOK Hint = "ok"
const HintWarn Hint = "warn"

var enumValues_Hint = []interface{}{
	"ok",
	"warn",
	"err",
	"accent",
	"dim",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Hint) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Hint {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Hint, v)
	}
	*j = Hint(v)
	return nil
}

type LineChart struct {
	// DataHash corresponds to the JSON schema field "data_hash".
	DataHash string `json:"data_hash" yaml:"data_hash" mapstructure:"data_hash"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Series corresponds to the JSON schema field "series".
	Series []LineChartSeriesElem `json:"series" yaml:"series" mapstructure:"series"`
}

type LineChartSeriesElem struct {
	// Hint corresponds to the JSON schema field "hint".
	Hint *Hint `json:"hint,omitempty,omitzero" yaml:"hint,omitempty" mapstructure:"hint,omitempty"`

	// Label corresponds to the JSON schema field "label".
	Label string `json:"label" yaml:"label" mapstructure:"label"`

	// Points corresponds to the JSON schema field "points".
	Points []LineChartSeriesElemPointsElem `json:"points" yaml:"points" mapstructure:"points"`
}

type LineChartSeriesElemPointsElem struct {
	// X corresponds to the JSON schema field "x".
	X float64 `json:"x" yaml:"x" mapstructure:"x"`

	// Y corresponds to the JSON schema field "y".
	Y float64 `json:"y" yaml:"y" mapstructure:"y"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LineChartSeriesElemPointsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["x"]; raw != nil && !ok {
		return fmt.Errorf("field x in LineChartSeriesElemPointsElem: required")
	}
	if _, ok := raw["y"]; raw != nil && !ok {
		return fmt.Errorf("field y in LineChartSeriesElemPointsElem: required")
	}
	type Plain LineChartSeriesElemPointsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = LineChartSeriesElemPointsElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LineChartSeriesElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["label"]; raw != nil && !ok {
		return fmt.Errorf("field label in LineChartSeriesElem: required")
	}
	if _, ok := raw["points"]; raw != nil && !ok {
		return fmt.Errorf("field points in LineChartSeriesElem: required")
	}
	type Plain LineChartSeriesElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = LineChartSeriesElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *LineChart) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["data_hash"]; raw != nil && !ok {
		return fmt.Errorf("field data_hash in LineChart: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in LineChart: required")
	}
	if _, ok := raw["series"]; raw != nil && !ok {
		return fmt.Errorf("field series in LineChart: required")
	}
	type Plain LineChart
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Kind != "line" {
		return fmt.Errorf("field %s: must be equal to %s", "kind", "line")
	}
	*j = LineChart(plain)
	return nil
}

type MetricKind string

const MetricKindCounter MetricKind = "counter"
const MetricKindGauge MetricKind = "gauge"
const MetricKindHistogram MetricKind = "histogram"

var enumValues_MetricKind = []interface{}{
	"counter",
	"histogram",
	"gauge",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MetricKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_MetricKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_MetricKind, v)
	}
	*j = MetricKind(v)
	return nil
}

// Single source of truth for all JSON-RPC 2.0 message shapes between
// milliways-term (Rust) and milliwaysd (Go). Types are codegen'd to
// internal/rpc/types.go and crates/milliways-term/milliways/src/rpc/types.rs by
// scripts/gen-rpc-types.sh. Per the design doc (Decision 3), all transport is
// newline-delimited JSON-RPC 2.0 over UDS. The top-level object is a virtual
// registry — every $defs type is exposed as a property so codegen tools
// (quicktype, others) can walk the schema and emit a type for each. Nothing on the
// wire actually uses this envelope shape; consumers only ever serialize individual
// $defs types as JSON-RPC params/results.
type MilliwaysJson struct {
	// AgentID corresponds to the JSON schema field "AgentId".
	AgentID *AgentID `json:"AgentId,omitempty,omitzero" yaml:"AgentId,omitempty" mapstructure:"AgentId,omitempty"`

	// AgentInfo corresponds to the JSON schema field "AgentInfo".
	AgentInfo *AgentInfo `json:"AgentInfo,omitempty,omitzero" yaml:"AgentInfo,omitempty" mapstructure:"AgentInfo,omitempty"`

	// AggregateContext corresponds to the JSON schema field "AggregateContext".
	AggregateContext *AggregateContext `json:"AggregateContext,omitempty,omitzero" yaml:"AggregateContext,omitempty" mapstructure:"AggregateContext,omitempty"`

	// BarsChart corresponds to the JSON schema field "BarsChart".
	BarsChart *BarsChart `json:"BarsChart,omitempty,omitzero" yaml:"BarsChart,omitempty" mapstructure:"BarsChart,omitempty"`

	// Bucket corresponds to the JSON schema field "Bucket".
	Bucket *Bucket `json:"Bucket,omitempty,omitzero" yaml:"Bucket,omitempty" mapstructure:"Bucket,omitempty"`

	// ChartData corresponds to the JSON schema field "ChartData".
	ChartData ChartData `json:"ChartData,omitempty,omitzero" yaml:"ChartData,omitempty" mapstructure:"ChartData,omitempty"`

	// ChartKind corresponds to the JSON schema field "ChartKind".
	ChartKind *ChartKind `json:"ChartKind,omitempty,omitzero" yaml:"ChartKind,omitempty" mapstructure:"ChartKind,omitempty"`

	// ContextSnapshot corresponds to the JSON schema field "ContextSnapshot".
	ContextSnapshot *ContextSnapshot `json:"ContextSnapshot,omitempty,omitzero" yaml:"ContextSnapshot,omitempty" mapstructure:"ContextSnapshot,omitempty"`

	// DonutChart corresponds to the JSON schema field "DonutChart".
	DonutChart *DonutChart `json:"DonutChart,omitempty,omitzero" yaml:"DonutChart,omitempty" mapstructure:"DonutChart,omitempty"`

	// Hint corresponds to the JSON schema field "Hint".
	Hint *Hint `json:"Hint,omitempty,omitzero" yaml:"Hint,omitempty" mapstructure:"Hint,omitempty"`

	// LineChart corresponds to the JSON schema field "LineChart".
	LineChart *LineChart `json:"LineChart,omitempty,omitzero" yaml:"LineChart,omitempty" mapstructure:"LineChart,omitempty"`

	// MetricKind corresponds to the JSON schema field "MetricKind".
	MetricKind *MetricKind `json:"MetricKind,omitempty,omitzero" yaml:"MetricKind,omitempty" mapstructure:"MetricKind,omitempty"`

	// PingResult corresponds to the JSON schema field "PingResult".
	PingResult *PingResult `json:"PingResult,omitempty,omitzero" yaml:"PingResult,omitempty" mapstructure:"PingResult,omitempty"`

	// ProtoVersion corresponds to the JSON schema field "ProtoVersion".
	ProtoVersion *ProtoVersion `json:"ProtoVersion,omitempty,omitzero" yaml:"ProtoVersion,omitempty" mapstructure:"ProtoVersion,omitempty"`

	// QuotaSnapshot corresponds to the JSON schema field "QuotaSnapshot".
	QuotaSnapshot *QuotaSnapshot `json:"QuotaSnapshot,omitempty,omitzero" yaml:"QuotaSnapshot,omitempty" mapstructure:"QuotaSnapshot,omitempty"`

	// RollupResponse corresponds to the JSON schema field "RollupResponse".
	RollupResponse *RollupResponse `json:"RollupResponse,omitempty,omitzero" yaml:"RollupResponse,omitempty" mapstructure:"RollupResponse,omitempty"`

	// RollupTier corresponds to the JSON schema field "RollupTier".
	RollupTier *RollupTier `json:"RollupTier,omitempty,omitzero" yaml:"RollupTier,omitempty" mapstructure:"RollupTier,omitempty"`

	// RoutingDecision corresponds to the JSON schema field "RoutingDecision".
	RoutingDecision *RoutingDecision `json:"RoutingDecision,omitempty,omitzero" yaml:"RoutingDecision,omitempty" mapstructure:"RoutingDecision,omitempty"`

	// SessionID corresponds to the JSON schema field "SessionId".
	SessionID *SessionID `json:"SessionId,omitempty,omitzero" yaml:"SessionId,omitempty" mapstructure:"SessionId,omitempty"`

	// Span corresponds to the JSON schema field "Span".
	Span *Span `json:"Span,omitempty,omitzero" yaml:"Span,omitempty" mapstructure:"Span,omitempty"`

	// SparklineChart corresponds to the JSON schema field "SparklineChart".
	SparklineChart *SparklineChart `json:"SparklineChart,omitempty,omitzero" yaml:"SparklineChart,omitempty" mapstructure:"SparklineChart,omitempty"`

	// Status corresponds to the JSON schema field "Status".
	Status *Status `json:"Status,omitempty,omitzero" yaml:"Status,omitempty" mapstructure:"Status,omitempty"`
}

type PingResult struct {
	// Pong corresponds to the JSON schema field "pong".
	Pong bool `json:"pong" yaml:"pong" mapstructure:"pong"`

	// Proto corresponds to the JSON schema field "proto".
	Proto ProtoVersion `json:"proto" yaml:"proto" mapstructure:"proto"`

	// UptimeS corresponds to the JSON schema field "uptime_s".
	UptimeS float64 `json:"uptime_s" yaml:"uptime_s" mapstructure:"uptime_s"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PingResult) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["pong"]; raw != nil && !ok {
		return fmt.Errorf("field pong in PingResult: required")
	}
	if _, ok := raw["proto"]; raw != nil && !ok {
		return fmt.Errorf("field proto in PingResult: required")
	}
	if _, ok := raw["uptime_s"]; raw != nil && !ok {
		return fmt.Errorf("field uptime_s in PingResult: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in PingResult: required")
	}
	type Plain PingResult
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Pong != true {
		return fmt.Errorf("field %s: must be equal to %t", "pong", true)
	}
	if 0 > plain.UptimeS {
		return fmt.Errorf("field %s: must be >= %v", "uptime_s", 0)
	}
	*j = PingResult(plain)
	return nil
}

type ProtoVersion struct {
	// Major corresponds to the JSON schema field "major".
	Major int `json:"major" yaml:"major" mapstructure:"major"`

	// Minor corresponds to the JSON schema field "minor".
	Minor int `json:"minor" yaml:"minor" mapstructure:"minor"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProtoVersion) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["major"]; raw != nil && !ok {
		return fmt.Errorf("field major in ProtoVersion: required")
	}
	if _, ok := raw["minor"]; raw != nil && !ok {
		return fmt.Errorf("field minor in ProtoVersion: required")
	}
	type Plain ProtoVersion
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.Major {
		return fmt.Errorf("field %s: must be >= %v", "major", 0)
	}
	if 0 > plain.Minor {
		return fmt.Errorf("field %s: must be >= %v", "minor", 0)
	}
	*j = ProtoVersion(plain)
	return nil
}

type QuotaSnapshot struct {
	// AgentID corresponds to the JSON schema field "agent_id".
	AgentID AgentID `json:"agent_id" yaml:"agent_id" mapstructure:"agent_id"`

	// Cap corresponds to the JSON schema field "cap".
	Cap float64 `json:"cap" yaml:"cap" mapstructure:"cap"`

	// Pct corresponds to the JSON schema field "pct".
	Pct float64 `json:"pct" yaml:"pct" mapstructure:"pct"`

	// Used corresponds to the JSON schema field "used".
	Used float64 `json:"used" yaml:"used" mapstructure:"used"`

	// Quota window e.g. '24h'.
	Window *string `json:"window,omitempty,omitzero" yaml:"window,omitempty" mapstructure:"window,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *QuotaSnapshot) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["agent_id"]; raw != nil && !ok {
		return fmt.Errorf("field agent_id in QuotaSnapshot: required")
	}
	if _, ok := raw["cap"]; raw != nil && !ok {
		return fmt.Errorf("field cap in QuotaSnapshot: required")
	}
	if _, ok := raw["pct"]; raw != nil && !ok {
		return fmt.Errorf("field pct in QuotaSnapshot: required")
	}
	if _, ok := raw["used"]; raw != nil && !ok {
		return fmt.Errorf("field used in QuotaSnapshot: required")
	}
	type Plain QuotaSnapshot
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.Cap {
		return fmt.Errorf("field %s: must be >= %v", "cap", 0)
	}
	if 100 < plain.Pct {
		return fmt.Errorf("field %s: must be <= %v", "pct", 100)
	}
	if 0 > plain.Pct {
		return fmt.Errorf("field %s: must be >= %v", "pct", 0)
	}
	if 0 > plain.Used {
		return fmt.Errorf("field %s: must be >= %v", "used", 0)
	}
	*j = QuotaSnapshot(plain)
	return nil
}

// Response from metrics.rollup.get.
type RollupResponse struct {
	// AgentID corresponds to the JSON schema field "agent_id".
	AgentID *AgentID `json:"agent_id,omitempty,omitzero" yaml:"agent_id,omitempty" mapstructure:"agent_id,omitempty"`

	// True when percentile fields above the raw tier are weighted-average
	// approximations. Always false at the raw tier. Always false for counter/gauge
	// kinds.
	Approximate bool `json:"approximate" yaml:"approximate" mapstructure:"approximate"`

	// Buckets corresponds to the JSON schema field "buckets".
	Buckets []Bucket `json:"buckets" yaml:"buckets" mapstructure:"buckets"`

	// Kind corresponds to the JSON schema field "kind".
	Kind MetricKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Metric corresponds to the JSON schema field "metric".
	Metric string `json:"metric" yaml:"metric" mapstructure:"metric"`

	// Tier corresponds to the JSON schema field "tier".
	Tier RollupTier `json:"tier" yaml:"tier" mapstructure:"tier"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RollupResponse) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["approximate"]; raw != nil && !ok {
		return fmt.Errorf("field approximate in RollupResponse: required")
	}
	if _, ok := raw["buckets"]; raw != nil && !ok {
		return fmt.Errorf("field buckets in RollupResponse: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in RollupResponse: required")
	}
	if _, ok := raw["metric"]; raw != nil && !ok {
		return fmt.Errorf("field metric in RollupResponse: required")
	}
	if _, ok := raw["tier"]; raw != nil && !ok {
		return fmt.Errorf("field tier in RollupResponse: required")
	}
	type Plain RollupResponse
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = RollupResponse(plain)
	return nil
}

type RollupTier string

const RollupTierDaily RollupTier = "daily"
const RollupTierHourly RollupTier = "hourly"
const RollupTierMonthly RollupTier = "monthly"
const RollupTierRaw RollupTier = "raw"
const RollupTierWeekly RollupTier = "weekly"

var enumValues_RollupTier = []interface{}{
	"raw",
	"hourly",
	"daily",
	"weekly",
	"monthly",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RollupTier) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RollupTier {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_RollupTier, v)
	}
	*j = RollupTier(v)
	return nil
}

// One sommelier routing decision for the aggregated /context strip.
type RoutingDecision struct {
	// Considered corresponds to the JSON schema field "considered".
	Considered []AgentID `json:"considered,omitempty,omitzero" yaml:"considered,omitempty" mapstructure:"considered,omitempty"`

	// Reason corresponds to the JSON schema field "reason".
	Reason *string `json:"reason,omitempty,omitzero" yaml:"reason,omitempty" mapstructure:"reason,omitempty"`

	// Selected corresponds to the JSON schema field "selected".
	Selected AgentID `json:"selected" yaml:"selected" mapstructure:"selected"`

	// Ts corresponds to the JSON schema field "ts".
	Ts time.Time `json:"ts" yaml:"ts" mapstructure:"ts"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RoutingDecision) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["selected"]; raw != nil && !ok {
		return fmt.Errorf("field selected in RoutingDecision: required")
	}
	if _, ok := raw["ts"]; raw != nil && !ok {
		return fmt.Errorf("field ts in RoutingDecision: required")
	}
	type Plain RoutingDecision
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = RoutingDecision(plain)
	return nil
}

// Daemon-assigned session identifier (UUID v4).
type SessionID string

// OTel-flavoured span row for the observability cockpit.
type Span struct {
	// Attributes corresponds to the JSON schema field "attributes".
	Attributes SpanAttributes `json:"attributes,omitempty,omitzero" yaml:"attributes,omitempty" mapstructure:"attributes,omitempty"`

	// DurationMs corresponds to the JSON schema field "duration_ms".
	DurationMs float64 `json:"duration_ms" yaml:"duration_ms" mapstructure:"duration_ms"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// ParentSpanID corresponds to the JSON schema field "parent_span_id".
	ParentSpanID *string `json:"parent_span_id,omitempty,omitzero" yaml:"parent_span_id,omitempty" mapstructure:"parent_span_id,omitempty"`

	// SpanID corresponds to the JSON schema field "span_id".
	SpanID string `json:"span_id" yaml:"span_id" mapstructure:"span_id"`

	// StartTs corresponds to the JSON schema field "start_ts".
	StartTs time.Time `json:"start_ts" yaml:"start_ts" mapstructure:"start_ts"`

	// Status corresponds to the JSON schema field "status".
	Status SpanStatus `json:"status" yaml:"status" mapstructure:"status"`

	// TraceID corresponds to the JSON schema field "trace_id".
	TraceID string `json:"trace_id" yaml:"trace_id" mapstructure:"trace_id"`
}

type SpanAttributes map[string]interface{}

type SpanStatus string

const SpanStatusError SpanStatus = "error"
const SpanStatusOK SpanStatus = "ok"
const SpanStatusUnset SpanStatus = "unset"

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpanStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SpanStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SpanStatus, v)
	}
	*j = SpanStatus(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Span) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["duration_ms"]; raw != nil && !ok {
		return fmt.Errorf("field duration_ms in Span: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Span: required")
	}
	if _, ok := raw["span_id"]; raw != nil && !ok {
		return fmt.Errorf("field span_id in Span: required")
	}
	if _, ok := raw["start_ts"]; raw != nil && !ok {
		return fmt.Errorf("field start_ts in Span: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return fmt.Errorf("field status in Span: required")
	}
	if _, ok := raw["trace_id"]; raw != nil && !ok {
		return fmt.Errorf("field trace_id in Span: required")
	}
	type Plain Span
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.DurationMs {
		return fmt.Errorf("field %s: must be >= %v", "duration_ms", 0)
	}
	*j = Span(plain)
	return nil
}

type SparklineChart struct {
	// DataHash corresponds to the JSON schema field "data_hash".
	DataHash string `json:"data_hash" yaml:"data_hash" mapstructure:"data_hash"`

	// Hint corresponds to the JSON schema field "hint".
	Hint *Hint `json:"hint,omitempty,omitzero" yaml:"hint,omitempty" mapstructure:"hint,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind string `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Points corresponds to the JSON schema field "points".
	Points []float64 `json:"points" yaml:"points" mapstructure:"points"`

	// Range corresponds to the JSON schema field "range".
	Range *SparklineChartRange `json:"range,omitempty,omitzero" yaml:"range,omitempty" mapstructure:"range,omitempty"`
}

type SparklineChartRange struct {
	// Max corresponds to the JSON schema field "max".
	Max float64 `json:"max" yaml:"max" mapstructure:"max"`

	// Min corresponds to the JSON schema field "min".
	Min float64 `json:"min" yaml:"min" mapstructure:"min"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SparklineChartRange) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["max"]; raw != nil && !ok {
		return fmt.Errorf("field max in SparklineChartRange: required")
	}
	if _, ok := raw["min"]; raw != nil && !ok {
		return fmt.Errorf("field min in SparklineChartRange: required")
	}
	type Plain SparklineChartRange
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = SparklineChartRange(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SparklineChart) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["data_hash"]; raw != nil && !ok {
		return fmt.Errorf("field data_hash in SparklineChart: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in SparklineChart: required")
	}
	if _, ok := raw["points"]; raw != nil && !ok {
		return fmt.Errorf("field points in SparklineChart: required")
	}
	type Plain SparklineChart
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Kind != "sparkline" {
		return fmt.Errorf("field %s: must be equal to %s", "kind", "sparkline")
	}
	*j = SparklineChart(plain)
	return nil
}

type StatusActiveAgent_0 = AgentID

var enumValues_SpanStatus = []interface{}{
	"ok",
	"error",
	"unset",
}

// Live cockpit state for the status bar. Returned by status.get and pushed by
// status.subscribe.
type Status struct {
	// Currently focused agent, or null if the focused pane is a shell.
	ActiveAgent interface{} `json:"active_agent" yaml:"active_agent" mapstructure:"active_agent"`

	// CostUsd corresponds to the JSON schema field "cost_usd".
	CostUsd float64 `json:"cost_usd" yaml:"cost_usd" mapstructure:"cost_usd"`

	// Count of error spans in the last 5 minutes.
	Errors5M int `json:"errors_5m" yaml:"errors_5m" mapstructure:"errors_5m"`

	// Proto corresponds to the JSON schema field "proto".
	Proto ProtoVersion `json:"proto" yaml:"proto" mapstructure:"proto"`

	// QuotaPct corresponds to the JSON schema field "quota_pct".
	QuotaPct float64 `json:"quota_pct" yaml:"quota_pct" mapstructure:"quota_pct"`

	// TokensIn corresponds to the JSON schema field "tokens_in".
	TokensIn int `json:"tokens_in" yaml:"tokens_in" mapstructure:"tokens_in"`

	// TokensOut corresponds to the JSON schema field "tokens_out".
	TokensOut int `json:"tokens_out" yaml:"tokens_out" mapstructure:"tokens_out"`

	// Number of dispatched prompts in the active session.
	Turn int `json:"turn" yaml:"turn" mapstructure:"turn"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Status) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["active_agent"]; raw != nil && !ok {
		return fmt.Errorf("field active_agent in Status: required")
	}
	if _, ok := raw["cost_usd"]; raw != nil && !ok {
		return fmt.Errorf("field cost_usd in Status: required")
	}
	if _, ok := raw["errors_5m"]; raw != nil && !ok {
		return fmt.Errorf("field errors_5m in Status: required")
	}
	if _, ok := raw["proto"]; raw != nil && !ok {
		return fmt.Errorf("field proto in Status: required")
	}
	if _, ok := raw["quota_pct"]; raw != nil && !ok {
		return fmt.Errorf("field quota_pct in Status: required")
	}
	if _, ok := raw["tokens_in"]; raw != nil && !ok {
		return fmt.Errorf("field tokens_in in Status: required")
	}
	if _, ok := raw["tokens_out"]; raw != nil && !ok {
		return fmt.Errorf("field tokens_out in Status: required")
	}
	if _, ok := raw["turn"]; raw != nil && !ok {
		return fmt.Errorf("field turn in Status: required")
	}
	type Plain Status
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.CostUsd {
		return fmt.Errorf("field %s: must be >= %v", "cost_usd", 0)
	}
	if 0 > plain.Errors5M {
		return fmt.Errorf("field %s: must be >= %v", "errors_5m", 0)
	}
	if 100 < plain.QuotaPct {
		return fmt.Errorf("field %s: must be <= %v", "quota_pct", 100)
	}
	if 0 > plain.QuotaPct {
		return fmt.Errorf("field %s: must be >= %v", "quota_pct", 0)
	}
	if 0 > plain.TokensIn {
		return fmt.Errorf("field %s: must be >= %v", "tokens_in", 0)
	}
	if 0 > plain.TokensOut {
		return fmt.Errorf("field %s: must be >= %v", "tokens_out", 0)
	}
	if 0 > plain.Turn {
		return fmt.Errorf("field %s: must be >= %v", "turn", 0)
	}
	*j = Status(plain)
	return nil
}
