// Copyright 2024 The milliways Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package sbom

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"
)

func TestGenerateSPDXIncludesGoCargoAndNPMPackages(t *testing.T) {
	workspace := t.TempDir()
	write(t, workspace, "go.mod", `module example.test/app

go 1.24

require (
	github.com/acme/lib v1.2.3
	golang.org/x/tools v0.30.0 // indirect
)
`)
	write(t, workspace, "Cargo.lock", `# This file is automatically @generated by Cargo.

[[package]]
name = "milliways-term"
version = "1.0.12"

[[package]]
name = "serde"
version = "1.0.203"
`)
	write(t, workspace, "package-lock.json", `{
  "name": "fixture",
  "lockfileVersion": 3,
  "packages": {
    "": {"name": "fixture", "version": "0.1.0"},
    "node_modules/@tanstack/router": {"version": "1.120.0"},
    "node_modules/left-pad": {"version": "1.3.0"},
    "node_modules/nested/node_modules/ignored": {"version": "9.9.9"}
  }
}`)

	doc, err := GenerateSPDX(GenerateOptions{
		Workspace: workspace,
		Now:       time.Date(2026, 5, 14, 12, 0, 0, 0, time.UTC),
	})
	if err != nil {
		t.Fatalf("GenerateSPDX: %v", err)
	}
	if doc.SPDXVersion != "SPDX-2.3" || doc.CreationInfo.Created != "2026-05-14T12:00:00Z" {
		t.Fatalf("unexpected document header: %#v", doc)
	}
	for _, want := range []struct {
		name    string
		version string
		source  string
	}{
		{"github.com/acme/lib", "v1.2.3", "go.mod"},
		{"golang.org/x/tools", "v0.30.0", "go.mod"},
		{"milliways-term", "1.0.12", "Cargo.lock"},
		{"serde", "1.0.203", "Cargo.lock"},
		{"@tanstack/router", "1.120.0", "package-lock.json"},
		{"left-pad", "1.3.0", "package-lock.json"},
	} {
		if !hasPackage(doc, want.name, want.version, want.source) {
			t.Fatalf("missing package %s %s from %s: %#v", want.name, want.version, want.source, doc.Packages)
		}
	}
	if hasPackage(doc, "ignored", "9.9.9", "package-lock.json") {
		t.Fatalf("nested node_modules package should be skipped: %#v", doc.Packages)
	}
}

func TestWriteSPDXJSON(t *testing.T) {
	doc, err := GenerateSPDX(GenerateOptions{Workspace: t.TempDir()})
	if err != nil {
		t.Fatalf("GenerateSPDX: %v", err)
	}
	var buf bytes.Buffer
	if err := WriteSPDXJSON(&buf, doc); err != nil {
		t.Fatalf("WriteSPDXJSON: %v", err)
	}
	var decoded SPDXDocument
	if err := json.Unmarshal(buf.Bytes(), &decoded); err != nil {
		t.Fatalf("invalid JSON: %v\n%s", err, buf.String())
	}
	if len(decoded.Packages) != 1 {
		t.Fatalf("packages = %d, want root package only", len(decoded.Packages))
	}
}

func TestWriteSPDXJSONFileCreatesParentDirectory(t *testing.T) {
	root := t.TempDir()
	doc, err := GenerateSPDX(GenerateOptions{Workspace: root})
	if err != nil {
		t.Fatalf("GenerateSPDX: %v", err)
	}
	path := filepath.Join(root, "dist", "milliways.spdx.json")
	if err := WriteSPDXJSONFile(path, doc); err != nil {
		t.Fatalf("WriteSPDXJSONFile: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if !bytes.Contains(data, []byte(`"spdxVersion": "SPDX-2.3"`)) {
		t.Fatalf("output is not SPDX JSON:\n%s", string(data))
	}
}

func hasPackage(doc SPDXDocument, name, version, source string) bool {
	for _, pkg := range doc.Packages {
		if pkg.Name == name && pkg.VersionInfo == version && pkg.Source == source {
			return true
		}
	}
	return false
}

func write(t *testing.T, root, rel, content string) {
	t.Helper()
	path := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("MkdirAll: %v", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}
}
