#!/usr/bin/env bash
# Regenerate Go and Rust RPC types from proto/milliways.json.
# Single source of truth: proto/milliways.json (JSON Schema 2020-12).
# CI fails if running this leaves a non-empty git diff.
set -euo pipefail

PROTO_VERSION_MAJOR=0
PROTO_VERSION_MINOR=1

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCHEMA="$ROOT/proto/milliways.json"
GO_OUT="$ROOT/internal/rpc/types.go"
RUST_OUT="$ROOT/crates/milliways-term/milliways/src/rpc/types.rs"

if [[ ! -f "$SCHEMA" ]]; then
    echo "error: $SCHEMA not found" >&2
    exit 1
fi

mkdir -p "$(dirname "$GO_OUT")"
mkdir -p "$(dirname "$RUST_OUT")"

# --- Go --------------------------------------------------------------------
# go-jsonschema (https://github.com/atombender/go-jsonschema) is a Go-native
# JSON Schema → Go struct generator. Offline-friendly (no npm), works on
# Node 25 hosts where quicktype currently fails with `s.codePointAt is not
# a function`.
GO_JSONSCHEMA="$(command -v go-jsonschema || true)"
if [[ -z "$GO_JSONSCHEMA" ]]; then
    if [[ -x "$(go env GOPATH 2>/dev/null)/bin/go-jsonschema" ]]; then
        GO_JSONSCHEMA="$(go env GOPATH)/bin/go-jsonschema"
    fi
fi
if [[ -z "$GO_JSONSCHEMA" ]]; then
    echo "error: 'go-jsonschema' not found." >&2
    echo "install: go install github.com/atombender/go-jsonschema@latest" >&2
    exit 2
fi

echo "generating $GO_OUT"
"$GO_JSONSCHEMA" \
    --package rpc \
    --capitalization ID \
    --capitalization URL \
    --capitalization MCP \
    --capitalization OK \
    --output "$GO_OUT" \
    "$SCHEMA"

# Add the license + version-stamp header. go-jsonschema writes its own
# header line, so we prepend ours after the fact.
HEADER="$(mktemp)"
trap 'rm -f "$HEADER"' EXIT
{
    echo "// Copyright 2024 The milliways Authors"
    echo "//"
    echo "// Licensed under the Apache License, Version 2.0 (the \"License\");"
    echo "// you may not use this file except in compliance with the License."
    echo "// You may obtain a copy of the License at"
    echo "//"
    echo "//     http://www.apache.org/licenses/LICENSE-2.0"
    echo "//"
    echo "// Unless required by applicable law or agreed to in writing, software"
    echo "// distributed under the License is distributed on an \"AS IS\" BASIS,"
    echo "// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied."
    echo "// See the License for the specific language governing permissions and"
    echo "// limitations under the License."
    echo
    echo "// Code generated by scripts/gen-rpc-types.sh from proto/milliways.json. DO NOT EDIT."
    echo "// Proto version: ${PROTO_VERSION_MAJOR}.${PROTO_VERSION_MINOR}"
    echo
    cat "$GO_OUT"
} > "$HEADER"
mv "$HEADER" "$GO_OUT"
trap - EXIT

# Sanity-check the output is valid Go.
if ! gofmt -l "$GO_OUT" >/dev/null 2>&1; then
    echo "error: generated $GO_OUT is not valid Go" >&2
    exit 3
fi

# --- Rust ------------------------------------------------------------------
# Rust codegen is deferred to Phase 1 of milliways-emulator-fork. The pinned
# choice will be `typify` (https://github.com/oxidecomputer/typify) — Oxide's
# JSON Schema → Rust serde struct generator, used in production. It runs as a
# build.rs dependency in the milliways-term crate, not as a one-shot binary,
# so it does not need to be invoked from this script.
#
# When typify is wired up in Phase 1, this section will become a stub that
# just prints "Rust types generated by build.rs" and exits 0.
echo "skipping $RUST_OUT — Rust codegen is wired into the build via typify in Phase 1"

# --- Summary ---------------------------------------------------------------
GO_LINES="$(wc -l < "$GO_OUT" | tr -d ' ')"
GO_TYPES="$(grep -c '^type ' "$GO_OUT" || true)"
echo "ok: $GO_OUT — $GO_LINES lines, $GO_TYPES type definitions"
echo
echo "if a CI 'codegen drift' job fails:"
echo "    1. ensure your local schema matches the PR's,"
echo "    2. re-run scripts/gen-rpc-types.sh,"
echo "    3. commit the generated files."
