#!/usr/bin/env bash
# install_local_swap.sh — install llama-swap so milliways' /local runner can
# hot-swap models on demand.
#
# Pre-req: scripts/install_local.sh has already been run (we need llama-server
# and at least one cached GGUF). This script downloads llama-swap, generates
# a config that lists every GGUF currently in $MODEL_DIR, and starts it as
# a foreground/background service on the same port milliways already expects.

set -euo pipefail

BIND_HOST="${BIND_HOST:-127.0.0.1}"
PORT="${PORT:-8765}"
# Resolve latest llama-swap release if version not pinned by caller.
if [ -z "${SWAP_VERSION:-}" ]; then
  SWAP_VERSION="$(curl -sSf https://api.github.com/repos/mostlygeek/llama-swap/releases/latest \
    | grep '"tag_name"' | cut -d'"' -f4 2>/dev/null)" || SWAP_VERSION="v211"
  [ -z "$SWAP_VERSION" ] && SWAP_VERSION="v211"
fi
MODEL_DIR="${MODEL_DIR:-$HOME/.local/share/milliways/models}"
LOG_DIR="${LOG_DIR:-$HOME/.local/share/milliways/local}"
CONFIG_DIR="${CONFIG_DIR:-$HOME/.config/milliways}"
SWAP_CONFIG="${SWAP_CONFIG:-$CONFIG_DIR/llama-swap.yaml}"
CTX_SIZE="${CTX_SIZE:-32768}"
# HOT_MODE=1 → never unload, warm every model on startup. Memory-heavy
# (each model stays resident in RAM/VRAM) but switches are sub-second.
# HOT_MODE=0 (default) → unload after TTL_SECONDS of inactivity. Memory-safe
# but every "first request after idle" pays a cold-load (~5–15s).
HOT_MODE="${HOT_MODE:-0}"
TTL_SECONDS="${TTL_SECONDS:-600}"

color() { printf '\033[1;%sm%s\033[0m\n' "$1" "$2"; }
info()  { color 36 "==> $*"; }
ok()    { color 32 "[ok] $*"; }
warn()  { color 33 "[!]  $*"; }
fail()  { color 31 "[x]  $*"; exit 1; }

OS="$(uname -s)"
ARCH="$(uname -m)"

port_in_use() {
  (echo > "/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1
}

# ---------------------------------------------------------------------------
# 1. Pre-flight: make sure install_local.sh has run.
# ---------------------------------------------------------------------------
preflight() {
  if ! command -v llama-server >/dev/null 2>&1; then
    fail "llama-server not found — run scripts/install_local.sh first"
  fi
  if [ ! -d "$MODEL_DIR" ] || [ -z "$(ls -A "$MODEL_DIR" 2>/dev/null | grep '\.gguf$')" ]; then
    fail "no GGUFs in $MODEL_DIR — run scripts/install_local.sh first"
  fi
}

# ---------------------------------------------------------------------------
# 2. Download llama-swap binary release.
# ---------------------------------------------------------------------------
install_llamaswap() {
  if command -v llama-swap >/dev/null 2>&1; then
    ok "llama-swap already installed: $(command -v llama-swap)"
    return
  fi

  local platform=""
  case "$OS" in
    Darwin)
      case "$ARCH" in
        arm64)  platform="darwin_arm64" ;;
        x86_64) platform="darwin_amd64" ;;
        *) fail "unsupported macOS arch: $ARCH" ;;
      esac
      ;;
    Linux)
      case "$ARCH" in
        x86_64)  platform="linux_amd64" ;;
        aarch64|arm64) platform="linux_arm64" ;;
        *) fail "unsupported Linux arch: $ARCH" ;;
      esac
      ;;
    *) fail "unsupported OS: $OS" ;;
  esac

  # Asset filenames use the bare version number (no 'v' prefix) even though the
  # tag has it: llama-swap_211_darwin_arm64.tar.gz at tag v211.
  local bare_ver="${SWAP_VERSION#v}"
  local url="https://github.com/mostlygeek/llama-swap/releases/download/${SWAP_VERSION}/llama-swap_${bare_ver}_${platform}.tar.gz"
  local tmp
  tmp="$(mktemp -d)"

  info "Downloading llama-swap $SWAP_VERSION ($platform)…"
  if ! curl -fL -o "$tmp/llama-swap.tar.gz" "$url"; then
    fail "download failed. Check $url is reachable and SWAP_VERSION is current."
  fi
  tar -xzf "$tmp/llama-swap.tar.gz" -C "$tmp"
  install -m 0755 "$tmp/llama-swap" "$HOME/.local/bin/llama-swap"
  rm -rf "$tmp"
  ok "llama-swap installed: $HOME/.local/bin/llama-swap"
}

# ---------------------------------------------------------------------------
# 3. Generate a config that registers every GGUF currently on disk.
#    llama-swap starts each model in its own llama-server child process when
#    a request for that model name arrives, and unloads after a TTL.
# ---------------------------------------------------------------------------
write_config() {
  mkdir -p "$CONFIG_DIR" "$LOG_DIR"

  # ttl: 0 in llama-swap means "never unload" — that's HOT mode.
  # In standby (default), we set the TTL to TTL_SECONDS and llama-swap
  # unloads after that long of inactivity to free RAM/VRAM.
  local ttl="$TTL_SECONDS"
  local mode_label="standby (unload after ${TTL_SECONDS}s idle)"
  if [ "$HOT_MODE" = "1" ]; then
    ttl=0
    mode_label="hot (never unload, warm at startup)"
  fi

  {
    cat <<EOF
# Auto-generated by scripts/install_local_swap.sh — re-run to refresh after
# downloading new GGUFs.
# Mode: $mode_label
healthCheckTimeout: 60
logLevel: info

models:
EOF

    # Each .gguf in $MODEL_DIR becomes a model entry. Alias = filename minus
    # the .gguf suffix and the GGUF/quant noise — a stable name that's easy
    # to type. e.g. "Qwen2.5-Coder-1.5B-Instruct-GGUF-Q4_K_M.gguf"
    #            -> "qwen2.5-coder-1.5b-instruct-q4_k_m"
    local internal_port=9100
    for gguf in "$MODEL_DIR"/*.gguf; do
      [ -e "$gguf" ] || continue
      local base
      base="$(basename "$gguf" .gguf)"
      local alias
      alias="$(printf '%s' "$base" | tr '[:upper:]' '[:lower:]' | sed 's/-gguf//; s/-instruct//')"
      cat <<EOF
  "$alias":
    cmd: |
      llama-server
      -m "$gguf"
      --host 127.0.0.1
      --port $internal_port
      --ctx-size $CTX_SIZE
      --jinja
    proxy: "http://127.0.0.1:$internal_port"
    ttl: $ttl
EOF
      internal_port=$((internal_port + 1))
    done
  } > "$SWAP_CONFIG"

  ok "wrote $SWAP_CONFIG (mode: $mode_label)"
}

# warm_models — issue a tiny chat-completion against every alias so llama-swap
# actually loads them. Only invoked when HOT_MODE=1.
warm_models() {
  [ "$HOT_MODE" = "1" ] || return 0
  info "Warming models so they're resident in memory…"
  # Wait for swap to be ready
  for i in $(seq 1 30); do
    if curl -sf "http://${BIND_HOST}:${PORT}/v1/models" >/dev/null 2>&1; then break; fi
    sleep 1
  done

  curl -sf "http://${BIND_HOST}:${PORT}/v1/models" \
    | python3 -c "import json,sys; [print(m['id']) for m in json.load(sys.stdin).get('data',[])]" 2>/dev/null \
    | while read -r alias; do
        info "  → loading $alias"
        curl -sf -X POST "http://${BIND_HOST}:${PORT}/v1/chat/completions" \
          -H 'Content-Type: application/json' \
          -d "{\"model\":\"$alias\",\"max_tokens\":1,\"messages\":[{\"role\":\"user\",\"content\":\"ok\"}]}" \
          >/dev/null 2>&1 || warn "  failed to warm $alias"
      done
  ok "warmup complete"
}

# ---------------------------------------------------------------------------
# 4. Service unit (launchd / systemd-user) replacing the single-model one
#    written by install_local.sh.
# ---------------------------------------------------------------------------
write_service() {
  if port_in_use "$PORT"; then
    warn "port $PORT is already in use — kill the existing milliways-local-server first"
    info "    pkill -f milliways-local-server"
    info "    launchctl unload ~/Library/LaunchAgents/dev.milliways.local.plist  # macOS"
    info "    systemctl --user stop milliways-local                              # Linux"
  fi

  cat > "$HOME/.local/bin/milliways-local-swap" <<EOF
#!/usr/bin/env bash
exec "\$HOME/.local/bin/llama-swap" --config "$SWAP_CONFIG" --listen "${BIND_HOST}:${PORT}"
EOF
  chmod +x "$HOME/.local/bin/milliways-local-swap"
  ok "wrote $HOME/.local/bin/milliways-local-swap"

  case "$OS" in
    Darwin)
      plist="$HOME/Library/LaunchAgents/dev.milliways.local-swap.plist"
      cat > "$plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>dev.milliways.local-swap</string>
  <key>ProgramArguments</key><array>
    <string>$HOME/.local/bin/milliways-local-swap</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$LOG_DIR/swap.log</string>
  <key>StandardErrorPath</key><string>$LOG_DIR/swap.err</string>
</dict>
</plist>
EOF
      ok "wrote launchd unit: $plist"
      info "Load with:   launchctl load -w $plist"
      info "Unload with: launchctl unload  $plist"
      ;;
    Linux)
      unit="$HOME/.config/systemd/user/milliways-local-swap.service"
      mkdir -p "$(dirname "$unit")"
      cat > "$unit" <<EOF
[Unit]
Description=milliways local model hot-swap proxy (llama-swap)

[Service]
ExecStart=$HOME/.local/bin/milliways-local-swap
Restart=on-failure
StandardOutput=append:$LOG_DIR/swap.log
StandardError=append:$LOG_DIR/swap.err

[Install]
WantedBy=default.target
EOF
      ok "wrote systemd unit: $unit"
      info "Enable with: systemctl --user enable --now milliways-local-swap"
      ;;
  esac
}

# ---------------------------------------------------------------------------
# 5. Smoke test — start swap, ask /v1/models, kill it.
# ---------------------------------------------------------------------------
smoke_test() {
  info "Starting llama-swap for a smoke test (up to 30s)…"
  "$HOME/.local/bin/milliways-local-swap" >"$LOG_DIR/swap-smoke.log" 2>&1 &
  local pid=$!
  trap 'kill $pid 2>/dev/null || true' EXIT

  for i in $(seq 1 30); do
    if ! kill -0 "$pid" 2>/dev/null; then
      warn "llama-swap exited during startup. Last 30 lines:"
      tail -30 "$LOG_DIR/swap-smoke.log" >&2 || true
      trap - EXIT
      return 1
    fi
    if curl -sf "http://${BIND_HOST}:${PORT}/v1/models" >/dev/null 2>&1; then
      ok "llama-swap responding on http://${BIND_HOST}:${PORT}/v1"
      curl -sf "http://${BIND_HOST}:${PORT}/v1/models" | sed 's/^/    /'
      kill "$pid" 2>/dev/null || true
      wait "$pid" 2>/dev/null || true
      trap - EXIT
      return 0
    fi
    sleep 1
  done

  warn "smoke test timed out — see $LOG_DIR/swap-smoke.log"
  kill "$pid" 2>/dev/null || true
  wait "$pid" 2>/dev/null || true
  trap - EXIT
  return 1
}

# ---------------------------------------------------------------------------
main() {
  info "milliways local-model swap installer (llama-swap)"
  info "Endpoint:   http://${BIND_HOST}:${PORT}/v1"
  info "Config:     $SWAP_CONFIG"
  info "Models:     $MODEL_DIR"
  if [ "$HOT_MODE" = "1" ]; then
    info "Mode:       HOT — models stay resident, sub-second switch"
  else
    info "Mode:       STANDBY — models unload after ${TTL_SECONDS}s, ~5–15s cold-load on first use"
    info "            (re-run with HOT_MODE=1 for always-resident)"
  fi
  echo

  preflight
  install_llamaswap
  write_config
  write_service
  smoke_test || warn "Smoke test did not pass — try: milliways-local-swap"
  if [ "$HOT_MODE" = "1" ]; then
    "$HOME/.local/bin/milliways-local-swap" >>"$LOG_DIR/swap.log" 2>&1 &
    local pid=$!
    warm_models
    kill "$pid" 2>/dev/null || true
    wait "$pid" 2>/dev/null || true
  fi

  echo
  ok "All set."
  info "Swap is wired up. From milliways:"
  info "  /local"
  info "  /models               # list every GGUF llama-swap can route to"
  info "  /model <alias>        # switch to that model"
  info "  /local-hot on|off     # toggle hot/standby at runtime"
  info ""
  info "Add more models by dropping a .gguf into $MODEL_DIR and re-running this script."
}

main "$@"
